openapi: "3.0.3"
info:
  title: spring boot template API
  version: v1

servers:
  - url: http://localhost:8080/v1
    description: V1 local server for development

paths:
  /widgets:
    get:
      summary: list all widgets
      operationId: list-widgets
      parameters:
        - name: offset
          in: query
          description: starting index when returning page of widgets
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: limit
          in: query
          description: number widgets to return in a page
          required: false
          schema:
            type: integer
            format: int32
            default: 100
      responses:
        '200':
          description: paged array of widgets
          headers:
            x-total-count:
              description: total number of widgets
              schema:
                type: integer
                format: int32
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Widgets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: create a widget
      operationId: create-widget
      responses:
        '201':
          description: created widget
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Widget"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /widgets/{id}:
    get:
      summary: specific widget
      operationId: get-widget-by-id
      parameters:
        - name: id
          in: path
          required: true
          description: the id of the widget to retrieve
          schema:
            type: string
      responses:
        '200':
          description: widget
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Widget"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Widget:
      type: object
      required:
        - id
        - description
        - cost
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        cost:
          $ref: "#/components/schemas/MonetaryAmount"
    MonetaryAmount:
      type: object
      required:
        - value
        - currency
      properties:
        value:
          type: number
        currency:
          type: string
    Widgets:
      type: array
      items:
        $ref: "#/components/schemas/Widget"
    Error:
      type: object
      required:
        - timestamp
        - status
        - error
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        error:
          type: string
        path:
          type: string
        detail:
          type: string