spring:
  mustache.check-template-location: false
  security.oauth2.resourceserver.jwt.issuer-uri: ${auth.issuer.url}
  main.banner-mode: "off"

management:
  endpoints.web.exposure.include: info,health
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true
