version: '3.9'
services:

  service-template-spring-app:
    profiles: ["app"]
    image: michaelruocco/service-template-spring-app:${APP_VERSION}
    container_name: service-template-spring-app
    ports:
      - 8099:8080
    environment:
      - SERVER_PORT=8080
      - AUTH_ISSUER_URL=http://keycloak:8091/auth/realms/demo-local
    profiles:
      - local-docker
    depends_on:
      - keycloak
      - otel-collector

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    command: ["-Djboss.http.port=8091"]
    ports:
      - 8091:8091
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/demo-local-realm.json
    volumes:
      - ../keycloak/demo-local-realm.json:/tmp/demo-local-realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8091/auth/realms/demo-local/.well-known/openid-configuration"]
      interval: 10s
      timeout: 10s
      retries: 15

  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ../monitoring/otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - wiremock

  wiremock:
    image: wiremock/wiremock:2.31.0-alpine
    container_name: wiremock
    command: ["--global-response-templating", "--verbose"]
    ports:
      - 4318:8080
    volumes:
      - ../wiremock:/home/wiremock