version: '3.9'
services:

  service-template-spring-app:
    image: michaelruocco/service-template-spring-app:${APP_VERSION}
    container_name: service-template-spring-app
    ports:
      - 8099:80
    environment:
      - SERVER_PORT=80