version: '3.9'
services:

  service-template-spring-app:
    image: michaelruocco/service-template-spring-app:${APP_VERSION}
    container_name: service-template-spring-app
    ports:
      - 8099:8080
    profiles:
      - local-docker
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    ports:
      - 8100:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/demo-local-realm.json
    volumes:
      - ../keycloak/demo-local-realm.json:/tmp/demo-local-realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8080/auth/realms/demo-local/.well-known/openid-configuration"]
      interval: 10s
      timeout: 10s
      retries: 15